import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by the FlutterFire CLI
import 'auth_gate.dart';

// The main function is the entry point for all Flutter apps.
void main() async {
  // Ensures that the Flutter binding is initialized before calling Firebase.
  WidgetsFlutterBinding.ensureInitialized();
  // Initializes Firebase services in your app.
  // The 'await' keyword means we'll wait for this to complete before running the app.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Runs the app.
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter To-Do App',
      debugShowCheckedModeBanner: false,
      // The theme sets the overall visual style of the app.
      theme: ThemeData(
        
        primaryColor: Color.fromARGB(255, 236, 159, 195),
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // The home of our app will be the AuthGate, which decides which screen to show.
      home: const AuthGate(),
    );
  }
}
